function read_CRF_norm_not_norm(cutoff,excludeSuppressed,plotErrorBars,roving,excludeNonmonotonic)
%Written by Xing 8/6/13, modified from read_ROC_old_new
%To compare results generated by data that is normalised or not normalised
%to maximum firing rates of individual channels, or to level of spontaneous or ISI activity. 
%Performs comparison of values of 4 params calculated by
%bj_cumulative_crf_diff.
%Set 'excludeNonmonotonic' to 1 to exclude blanco channels 14 & 55 from
%analysis (non-monotonic CRF).
calcThirdOnly=1;%compare firing rates between last third of per-flanker sessions and first third of flanker sessions
analysisType='CRF';
normaliseCh=0;
plotDiffC50_30=0;
newColCode=0;
calculateTangent=1;
startEndTime='_1024_to_1536';
onExternalHD=0;
if onExternalHD==1
    rootFolder='K:\PL_backup_190713';
else
    rootFolder='F:';
end
paramTexts=[{'slope'} {'C_5_0'} {'min'} {'max'}];
figGauss=figure('Color',[1,1,1],'Units','Normalized','Position',[0.1, 0.1, 0.45, 0.65]); %
set(figGauss, 'PaperUnits', 'centimeters', 'PaperType', 'A4', 'PaperOrientation', 'landscape', 'PaperPosition', [0.63452 3.305 3.325/0.4*0.45 3.305/5*65]);
animals=[{'blanco'} {'jack'}];
if roving==0
    areas=[{'v4_1'} {'v1_1'}];
    allTableStats=cell(1,1);
    allParTableStats=cell(1,1);
    mpallTableStats=cell(1,1);
elseif roving==1
    slopeThird=cell(1,length(animals));
    C50Third=cell(1,length(animals));
    minThird=cell(1,length(animals));
    maxThird=cell(1,length(animals));
    sampleThird=cell(1,length(animals));
    areaThird=cell(1,length(animals));
    area2=cell(1,length(animals));%to compare all flanker sessions with last third of pre-flanker and all of post-flanker
    area1=cell(1,length(animals));
    slope1=cell(1,length(animals));
    C501=cell(1,length(animals));
    min1=cell(1,length(animals));
    max1=cell(1,length(animals));
    slope2=cell(1,length(animals));
    C502=cell(1,length(animals));
    min2=cell(1,length(animals));
    max2=cell(1,length(animals));
    area3=cell(1,length(animals));
    slope3=cell(1,length(animals));
    C503=cell(1,length(animals));
    min3=cell(1,length(animals));
    max3=cell(1,length(animals));    
    allSlope=cell(1,length(animals));
    allC50=cell(1,length(animals));
    allMin=cell(1,length(animals));
    allMax=cell(1,length(animals));   
    allArea=cell(1,length(animals));   
    sample1=cell(1,length(animals));
    sample2=cell(1,length(animals));   
    sample3=cell(1,length(animals));   
    allSample=cell(1,length(animals));
    areas=[{'v1_2_1'} {'v1_2_2'} {'v1_2_3'}];
    areas=[{'v1_2_1'} {'v1_2_2'}];
    rovingCol=[0.5 0 0;0.75 0 0;1 0 0];
    rovingCol=[1 0 0;10/255 170/255 60/255;0 0 1];
    if newColCode==1
        taskCols=[204/256 153/256 256/256;255/256 222/256 173/256;154/256 205/256 50/256];%purple;orange;green
        taskColsDark=[153/256 50/256 204/256;210/256 105/256 30/256;34/256 139/256 34/256];%purple;orange;green
    end
    allTableStats=cell(1,3);
    allParTableStats=cell(1,3);
    mpallTableStats=cell(1,3);
end
for areaInd=1:length(areas)
    area=areas{areaInd};
    [sampleContrasts testContrasts]=area_metadata(area);
    if newColCode==1
        taskCol=taskCols(areaInd,:);
        taskColDark=taskColsDark(areaInd,:);
        markerFaceTypes=[{'none'} {taskCol} {taskColDark}];
    end
    for animalInd=1:length(animals)
        animal=animals{animalInd};
        for sampleContrastsInd=1:length(sampleContrasts)
            sampleContrast=sampleContrasts(sampleContrastsInd);
            testContrast=testContrasts(sampleContrastsInd,:);
            if newColCode==1
                if sampleContrast==30
                    markerFaceType=markerFaceTypes{2};
                elseif sampleContrast==20
                    markerFaceType=markerFaceTypes{1};
                elseif sampleContrast==40
                    markerFaceType=markerFaceTypes{3};
                end
            end
            subFolder='crf_meanchannels';
            loadText=['load ',rootFolder,'\PL\',analysisType,'\',animal,'\',subFolder,'\cumulative_CRFs_old_new_',area,'_',subFolder,'_cutoff',num2str(cutoff*10),'.mat'];
            loadText=['load ',rootFolder,'\PL\',analysisType,'\',animal,'\',subFolder,'\cumulative_CRFs_old_new_',area,'_',num2str(sampleContrast),'_cutoff',num2str(cutoff*10),'.mat'];
            if excludeNonmonotonic
                loadText=['load ',rootFolder,'\PL\',analysisType,'\',animal,'\crf_meanchannels_excludeNonMonotonic\cumulative_CRFs_old_new_',area,'_',num2str(sampleContrast),'_cutoff',num2str(cutoff*10),'.mat'];
            end
            eval(loadText)%read non-normalised data
            oldValues=[slopeNeuroNew;PNENew;minRateNew;maxRateNew];%values calculated using trial-wise method ('new') but not normalised, so assigned to 'old' variable
            slopeNeuroOld=slopeNeuroNew;
            PNEOld=PNENew;
            minRateOld=minRateNew;
            maxRateOld=maxRateNew;
            oldAllMeanEpoch4AcrossTrials=allMeanEpoch4AcrossTrials;
        
            if roving==1%compare activity levels from last third of flankerless sessions against first third of flanker sessions
                numThirdSess=floor(size(oldValues,2)*0.3);
                if strcmp(area,'v1_2_1')%last third of pre-flanker sessions
                    sampleThird{animalInd}=[sampleThird{animalInd} zeros(1,numThirdSess)+sampleContrastsInd];
                    slopeThird{animalInd}=[slopeThird{animalInd} slopeNeuroNew(end-numThirdSess+1:end)];
                    C50Third{animalInd}=[C50Third{animalInd} PNENew(end-numThirdSess+1:end)];
                    minThird{animalInd}=[minThird{animalInd} minRateNew(end-numThirdSess+1:end)];
                    maxThird{animalInd}=[maxThird{animalInd} maxRateNew(end-numThirdSess+1:end)];
                    areaThird{animalInd}=[areaThird{animalInd} zeros(1,numThirdSess)+1];
                    slope1{animalInd}=[slope1{animalInd} slopeNeuroNew(end-numThirdSess+1:end)];
                    C501{animalInd}=[C501{animalInd} PNENew(end-numThirdSess+1:end)];
                    min1{animalInd}=[min1{animalInd} minRateNew(end-numThirdSess+1:end)];
                    max1{animalInd}=[max1{animalInd} maxRateNew(end-numThirdSess+1:end)];
                    area1{animalInd}=[area1{animalInd} zeros(1,numThirdSess)+1];
                    sample1{animalInd}=[sample1{animalInd} zeros(1,numThirdSess)+sampleContrastsInd];
                elseif strcmp(area,'v1_2_2')%first third of flanker sessions
                    sampleThird{animalInd}=[sampleThird{animalInd} zeros(1,numThirdSess)+sampleContrastsInd];
                    slopeThird{animalInd}=[slopeThird{animalInd} slopeNeuroNew(1:numThirdSess)];
                    C50Third{animalInd}=[C50Third{animalInd} PNENew(1:numThirdSess)];
                    minThird{animalInd}=[minThird{animalInd} minRateNew(1:numThirdSess)];
                    maxThird{animalInd}=[maxThird{animalInd} maxRateNew(1:numThirdSess)];
                    areaThird{animalInd}=[areaThird{animalInd} zeros(1,numThirdSess)+2];
                    slope2{animalInd}=[slope2{animalInd} slopeNeuroNew];%store all of flanker data
                    C502{animalInd}=[C502{animalInd} PNENew];
                    min2{animalInd}=[min2{animalInd} minRateNew];
                    max2{animalInd}=[max2{animalInd} maxRateNew];
                    area2{animalInd}=[area2{animalInd} zeros(1,length(slopeNeuroNew))+2];
                    sample2{animalInd}=[sample2{animalInd} zeros(1,length(slopeNeuroNew))+sampleContrastsInd];
                elseif strcmp(area,'v1_2_3')
                    slope3{animalInd}=[slope3{animalInd} slopeNeuroNew];%store all of post-flanker data
                    C503{animalInd}=[C503{animalInd} PNENew];
                    min3{animalInd}=[min3{animalInd} minRateNew];
                    max3{animalInd}=[max3{animalInd} maxRateNew]; 
                    area3{animalInd}=[area3{animalInd} zeros(1,length(slopeNeuroNew))+3];   
                    sample3{animalInd}=[sample3{animalInd} zeros(1,length(slopeNeuroNew))+sampleContrastsInd];
                end                                
            end
%         subFolder=[subFolder,'_normISI'];
%         if normaliseCh
%             subFolder=[subFolder,'_normCh'];
%         end
%         if excludeSuppressed
%             subFolder=[subFolder,'_excludeSuppressed'];
%         end
            subFolder=[subFolder,'_normSpontan'];%read normalised data
            loadText=['load ',rootFolder,'\PL\',analysisType,'\',animal,'\',subFolder,'\cumulative_CRFs_old_new_',area,'_',subFolder,'_cutoff',num2str(cutoff*10),'.mat allMeanEpoch4AcrossTrials'];  
            loadText=['load ',rootFolder,'\PL\',analysisType,'\',animal,'\',subFolder,'\cumulative_CRFs_old_new_',area,'_',num2str(sampleContrast),'_cutoff',num2str(cutoff*10),'.mat allMeanEpoch4AcrossTrials'];
            loadText=['load ',rootFolder,'\PL\',analysisType,'\',animal,'\',subFolder,'\cumulative_CRFs_old_new_',area,'_',num2str(sampleContrast),'_cutoff',num2str(cutoff*10),'.mat'];
            if excludeNonmonotonic
                loadText=['load ',rootFolder,'\PL\',analysisType,'\',animal,'\crf_meanchannels_excludeNonMonotonic\cumulative_CRFs_old_new_',area,'_',num2str(sampleContrast),'_cutoff',num2str(cutoff*10),'.mat'];
            end
            eval(loadText)
            newValues=[slopeNeuroNew;PNENew;minRateNew;maxRateNew];%values calculated using trial-wise method
            if ~calcThirdOnly==1
                %plot CRF values for each analysis type:
                figure('Color',[1,1,1],'Units','Normalized','Position',[0.1, 0.1, 0.8, 0.8]); %
                %         set(figROC, 'PaperUnits', 'centimeters', 'PaperType', 'A4', 'PaperOrientation', 'landscape', 'PaperPosition', [0.63452 0.63452 6.65 3.305]);
                setCol='br';
                for comparisonSet=1:2
                    sessionCounter=1;
                    for i=1:size(allMeanEpoch4AcrossTrials,1)
                        subplot(ceil(size(allMeanEpoch4AcrossTrials,1)/5),5,sessionCounter);
                        if comparisonSet==1
                            meanEpoch4AcrossTrials=oldAllMeanEpoch4AcrossTrials(i,2:end);
                        elseif comparisonSet==2
                            meanEpoch4AcrossTrials=allMeanEpoch4AcrossTrials(i,2:end);
                        end
                        if plotErrorBars==1
                            errorbar(testContrast,meanEpoch4AcrossTrials,stdEpoch4AcrossTrials,setCol(comparisonSet),'LineStyle','none');%errorbar(X,Y,E) plots Y versus X with symmetric error bars 2*E(i) long
                            hold on
                        end
                        plot(testContrast,meanEpoch4AcrossTrials,'Marker','o','Color',setCol(comparisonSet),'LineStyle','none');
                        hold on
                        xlim([0 max(testContrast)+10]);
                        if sessionCounter==10%||sessionCounter==11||sessionCounter==18
                            %                                                 pause
                        end
                        [slopeNeuroNew,PNENew,diffPNENew,minRateNew,maxRateNew,chSSENew]=nr_fitting(meanEpoch4AcrossTrials,sampleContrast,testContrast,sessionCounter,slopeNeuroNew,chSSENew,PNENew,minRateNew,maxRateNew,diffPNENew,plotDiffC50_30,calculateTangent,startEndTime,animal,area);
                        if sessionCounter==1
                            xlabel('contrast (%)');
                            ylabel('firing rate (spikes/s)');
                        end
                        sessionCounter=sessionCounter+1;
                        title(num2str(i),'FontSize',16);
                    end
                end
                imagename=[animal,'_',area,'_','_norm_notNormSpon_CRF_4_params_sessions_cutoff',num2str(cutoff*10)];
                if excludeSuppressed==1
                    imagename=[animal,'_',area,'_','_norm_notNormSpon_CRF_4_params_sessions_cutoff',num2str(cutoff*10),'_excludeSuppressed'];
                end
                pathname=fullfile(rootFolder,'PL',analysisType,imagename);
                printtext=sprintf('print -dpng %s.png',pathname);
                set(gcf,'PaperPositionMode','auto')
                eval(printtext);
            end

            %compare non-normalised vs normalised values:
            figure(figGauss)                
            [hS,pS,ciS,statsS]=ttest(slopeNeuroNew,slopeNeuroOld)
            [hP,pP,ciP,statsP]=ttest(PNENew,PNEOld)
            [hmin,pmin,cimin,statsmin]=ttest(minRateNew,minRateOld)
            [hmax,pmax,cimax,statsmax]=ttest(maxRateNew,maxRateOld)
            dfs=[statsS.df statsP.df statsmin.df statsmax.df];
            tvals=[statsS.tstat statsP.tstat statsmin.tstat statsmax.tstat];
            pvals=[pS pP pmin pmax];
            for paramInd=1:4
                if roving==0
                    subplot(4,4,(paramInd-1)*4+animalInd+(areaInd-1)*2);
                    %calculate mean, SD for each parameter, for new & old methods:
                    tableStats(paramInd,1)=mean(oldValues(paramInd,:));
                    tableStats(paramInd,2)=std(oldValues(paramInd,:));
                    tableStats(paramInd,3)=mean(newValues(paramInd,:));
                    tableStats(paramInd,4)=std(newValues(paramInd,:));
                    %t-test stats for difference between old & new values:
                    tableStats(paramInd,5)=dfs(paramInd);
                    tableStats(paramInd,6)=tvals(paramInd);
                    tableStats(paramInd,7)=pvals(paramInd);
    %             plot(1:length(slopeNeuroNew),newValues(paramInd,:),'ro','LineStyle','none','MarkerFaceColor','r');hold on
    %             plot(1:length(slopeNeuroNew),oldValues(paramInd,:),'bo','LineStyle','none','MarkerFaceColor','b');
    %             plot(1:length(slopeNeuroNew),newValues(paramInd,:),'rx','LineStyle','none');hold on
    %             plot(1:length(slopeNeuroNew),oldValues(paramInd,:),'bx','LineStyle','none','MarkerSize',7);
    %             plot(1:length(slopeNeuroNew),oldValues(paramInd,:),'bx','LineStyle','none','MarkerSize',7);hold on
    %             plot(1:length(slopeNeuroNew),newValues(paramInd,:),'r+','LineStyle','none');
                    plot(1:length(slopeNeuroNew),newValues(paramInd,:),'ro','LineStyle','none');hold on
    %             plot(1:length(slopeNeuroNew),oldValues(paramInd,:),'rx','LineStyle','none','MarkerSize',7);%not normalised
    %             plot(1:length(slopeNeuroNew),newValues(paramInd,:),'ro','LineStyle','none');hold on
    %             plot(1:length(slopeNeuroNew),oldValues(paramInd,:),'bx','LineStyle','none','MarkerSize',7);
                elseif roving==1
%                     subplot(4,4,(paramInd-1)*4+animalInd+(areaInd-1)*2);
%                     plot(1:length(slopeNeuroNew),newValues(paramInd,:),'Marker','o','Color',rovingCol(sampleContrastsInd,:),'LineStyle','none');hold on
                    if newColCode==0
                        subplot(4,4,(paramInd-1)*4+animalInd+(areaInd-1)*2);
                    elseif newColCode==1
                        subplot(4,2,(paramInd-1)*2+animalInd);%plot values for stages without and with flankers on same subplot
                        if areaInd==1
                            startPointSave(animalInd)=length(slopeNeuroNew)+1;%keep track of flankerless sessions
                            startPoint=0;
                        elseif areaInd==2
                            startPoint=startPointSave(animalInd);
                            startPointSave2(animalInd)=length(slopeNeuroNew);%keep track of flankerless+flanker sessions
                        elseif areaInd==3
                            startPoint=startPointSave(animalInd)+startPointSave2(animalInd);
                        end
                    end
                    if newColCode==0
                        plot(1:length(slopeNeuroNew),newValues(paramInd,:),'Marker','o','Color',rovingCol(sampleContrastsInd,:),'LineStyle','none');hold on
                    elseif newColCode==1
                        plot(1+startPoint:length(slopeNeuroNew)+startPoint,newValues(paramInd,:),'Marker','o','MarkerEdgeColor',taskColDark,'LineStyle','none','MarkerFaceColor',markerFaceType);hold on
                    end
                end
                if newColCode==0
                    xlim([0 length(slopeNeuroNew)+1]);
                    axis square
                elseif newColCode==1
                    xlim([0 length(slopeNeuroNew)+startPoint+1]);
                end
                if strcmp(animal,'blanco')&&strcmp(area,'v4_1')||strcmp(animal,'blanco')&&strcmp(area,'v1_2_1')&&sampleContrastsInd==1
                    ylabel(paramTexts(paramInd));
                    if paramInd==1
                        xlabel('session number');
                    end
                end
            end
            %calculate partial correlations for each parameter (based on new data only):
            [rho p]=partialcorr(slopeNeuroNew',(1:length(slopeNeuroNew))',[PNENew' minRateNew' maxRateNew'])
            parTableStats(1,8:10)=[length(slopeNeuroNew)-2 rho p];
            [rho p]=partialcorr(PNENew',(1:length(PNENew))',[slopeNeuroNew' minRateNew' maxRateNew'])
            parTableStats(2,8:10)=[length(PNENew)-2 rho p];
            [rho p]=partialcorr(minRateNew',(1:length(minRateNew))',[slopeNeuroNew' PNENew' maxRateNew'])
            parTableStats(3,8:10)=[length(minRateNew)-2 rho p];
            [rho p]=partialcorr(maxRateNew',(1:length(maxRateNew))',[slopeNeuroNew' PNENew' minRateNew'])
            parTableStats(4,8:10)=[length(maxRateNew)-2 rho p];
            allParTableStats{sampleContrastsInd}=[allParTableStats{sampleContrastsInd};parTableStats];
            %calculate regular correlations 
            [rho p]=corr(slopeNeuroNew',(1:length(slopeNeuroNew))','type','Spearman')
            tableStats(1,8:10)=[length(slopeNeuroNew)-2 rho p];
            [rho p]=corr(PNENew',(1:length(PNENew))','type','Spearman')
            tableStats(2,8:10)=[length(PNENew)-2 rho p];
            [rho p]=corr(minRateNew',(1:length(minRateNew))','type','Spearman')
            tableStats(3,8:10)=[length(minRateNew)-2 rho p];
            [rho p]=corr(maxRateNew',(1:length(maxRateNew))','type','Spearman')
            tableStats(4,8:10)=[length(maxRateNew)-2 rho p];
            allTableStats{sampleContrastsInd}=[allTableStats{sampleContrastsInd};tableStats];  
            %calculate meaningful partial correlations
            [rho p]=partialcorr(slopeNeuroNew',(1:length(slopeNeuroNew))',[minRateNew' maxRateNew'])
            mptableStats(1,8:10)=[length(slopeNeuroNew)-2 rho p];
            [rho p]=partialcorr(PNENew',(1:length(PNENew))',[minRateNew' maxRateNew'])
            mptableStats(2,8:10)=[length(PNENew)-2 rho p];
            [rho p]=partialcorr(minRateNew',(1:length(minRateNew))',[slopeNeuroNew' maxRateNew'])
            mptableStats(3,8:10)=[length(minRateNew)-2 rho p];
            [rho p]=partialcorr(maxRateNew',(1:length(maxRateNew))',[slopeNeuroNew' minRateNew'])
            mptableStats(4,8:10)=[length(maxRateNew)-2 rho p];
            mpallTableStats{sampleContrastsInd}=[mpallTableStats{sampleContrastsInd};mptableStats];   
        end
    end
end
if roving==0||newColCode==0
    subplot(4,4,1);
    title('             monkey 1');
    subplot(4,4,2);
    title('             monkey 2');
    subplot(4,4,3);
    title('             monkey 1');
    subplot(4,4,4);
    title('             monkey 2');
elseif newColCode==1
    subplot(4,2,1);
    xlabel('Session number');
    ylabel('Slope');
    title('Monkey 1');
    subplot(4,2,2);
    title('Monkey 2');
    subplot(4,2,3);
    ylabel('C_5_0');
    subplot(4,2,5);
    ylabel('Minimum');
    subplot(4,2,7);
    ylabel('Maximum');
end
%     subplot(4,4,1);
%     xlabel('contrast (%)');
%     ylabel('slope');
%     title('monkey 1');
%     subplot(4,4,2);
%     title('monkey 2');
%     subplot(4,4,3);
%     title('monkey 1');
%     subplot(4,4,4);
%     title('monkey 2');
%     subplot(4,4,5);
%     ylabel('PNE');
%     subplot(4,4,9);
%     ylabel('minimum');
%     subplot(4,4,13);
%     ylabel('maximum');
if roving==1
    if newColCode==0
        subplot(4,4,1);
        ylim([0 0.012]);
        subplot(4,4,3);
        ylim([0 0.012]);
        subplot(4,4,5);
        ylim([20 70]);
        subplot(4,4,6);
        ylim([25 50]);
        subplot(4,4,7);
        ylim([10 60]);
        subplot(4,4,8);
        ylim([35 55]);
        subplot(4,4,9);
        ylim([5 18]);
        subplot(4,4,10);
        ylim([5 15]);
        subplot(4,4,11);
        ylim([8 15]);
        subplot(4,4,12);
        ylim([8 15]);
        subplot(4,4,15);
        ylim([0 25]);
        subplot(4,4,16);
        ylim([15 40]);
    elseif newColCode==1
        subplot(4,2,1)
        ylim([0 0.011])
        subplot(4,2,2)
        ylim([0 0.011])
        subplot(4,2,3)
        ylim([10 70])
        subplot(4,2,4)
        ylim([20 60])
        subplot(4,2,5)
        ylim([10 17])
        subplot(4,2,6)
        ylim([6 15])
        subplot(4,2,2);
        text(1,0.004,'no flankers')
        plot(1,0.003,'Marker','o','MarkerEdgeColor',taskColsDark(1,:),'MarkerFaceColor',taskColsDark(1,:));
        plot(1,0.002,'Marker','o','MarkerEdgeColor',taskColsDark(1,:),'MarkerFaceColor',taskCols(1,:));
        plot(1,0.001,'Marker','o','MarkerEdgeColor',taskColsDark(1,:),'MarkerFaceColor','none');
        text(2,0.003,'40%')
        text(2,0.002,'30%')
        text(2,0.001,'20%')
        text(11,0.004,'flankers')
        plot(11,0.003,'Marker','o','MarkerEdgeColor',taskColsDark(2,:),'MarkerFaceColor',taskColsDark(2,:));
        plot(11,0.002,'Marker','o','MarkerEdgeColor',taskColsDark(2,:),'MarkerFaceColor',taskCols(2,:));
        plot(11,0.001,'Marker','o','MarkerEdgeColor',taskColsDark(2,:),'MarkerFaceColor','none');
        text(12,0.003,'40%')
        text(12,0.002,'30%')
        text(12,0.001,'20%')
        pause
        subplot(4,2,1);
        xlim([0 35]);
        subplot(4,2,2);
        xlim([0 17]);
        subplot(4,2,3);
        xlim([0 35]);
        subplot(4,2,4);
        xlim([0 17]);
        subplot(4,2,5);
        xlim([0 35]);
        subplot(4,2,6);
        xlim([0 17]);
        subplot(4,2,7);
        xlim([0 35]);
        subplot(4,2,8);
        xlim([0 17]);     
    end
end
% subplot(4,4,3);
% ylim([0.0025 0.007]);
% subplot(4,4,4);
% ylim([0.011 0.019]);
% subplot(4,4,8);
% ylim([33 40]);
% subplot(4,4,9);
% ylim([-0.4 0.4]);
% subplot(4,4,10);
% ylim([-0.2 0.5]);
% subplot(4,4,11);
% ylim([-0.2 0.4]);
% subplot(4,4,13);
% ylim([0.2 1]);
% subplot(4,4,14);
% ylim([0.2 0.8]);
% subplot(4,4,16);
% ylim([0.78 1]);
% %ignore outliers:
% subplot(4,4,9);
% ylim([0.05 0.4]);
% subplot(4,4,10);
% ylim([0.25 0.45]);
% subplot(4,4,13);
% ylim([0.2 0.6]);
% subplot(4,4,14);
% ylim([0.2 0.5]);
imagename=['bj_old_new_ROC_4_params_sessions_cutoff',num2str(cutoff*10)];
if excludeSuppressed==1
    imagename=['bj_old_new_ROC_4_params_sessions_cutoff',num2str(cutoff*10),'_excludeSuppressed'];
end
if roving==1
    imagename=[imagename,'_roving'];
end
if excludeNonmonotonic==1
    imagename=[imagename,'_excludeNonmonotonic'];
end
pathname=fullfile(rootFolder,'PL','ROC',imagename);
printtext=sprintf('print -dpng %s.png',pathname);
set(gcf,'PaperPositionMode','auto')
% eval(printtext);
cutoff
allTableStats

allStatsTable=[];
figure;
for animalInd=1:2
    [p,t,stats]=anovan(slopeThird{animalInd},{areaThird{animalInd},sampleThird{animalInd},},'model','full');
    [c,m] = multcompare(stats)
    [p,t,stats]=anovan(C50Third{animalInd},{areaThird{animalInd},sampleThird{animalInd},},'model','full');
    [c,m] = multcompare(stats)
    [p,t,stats]=anovan(minThird{animalInd},{areaThird{animalInd},sampleThird{animalInd},},'model','full');
    [c,m] = multcompare(stats)
    [p,t,stats]=anovan(maxThird{animalInd},{areaThird{animalInd},sampleThird{animalInd},},'model','full');
    [c,m] = multcompare(stats)
    %to compare all flanker sessions with last third of pre-flanker and all
    %of post-flanker:
    allSlope{animalInd}=[slope1{animalInd} slope2{animalInd} slope3{animalInd}];
    allC50{animalInd}=[C501{animalInd} C502{animalInd} C503{animalInd}];
    allMin{animalInd}=[min1{animalInd} min2{animalInd} min3{animalInd}];
    allMax{animalInd}=[max1{animalInd} max2{animalInd} max3{animalInd}];
    allArea{animalInd}=[area1{animalInd} area2{animalInd} area3{animalInd}];
    allSample{animalInd}=[sample1{animalInd} sample2{animalInd} sample3{animalInd}];
    [p,t,stats]=anovan(allSlope{animalInd},{allArea{animalInd},allSample{animalInd},},'model','full');
    [c,m] = multcompare(stats)
    allStatsTable=[allStatsTable;t(2,3) t(5,3) t(2,6) p(1)];
    [p,t,stats]=anovan(allC50{animalInd},{allArea{animalInd},allSample{animalInd},},'model','full');
    [c,m] = multcompare(stats)
    allStatsTable=[allStatsTable;t(2,3) t(5,3) t(2,6) p(1)];
    [p,t,stats]=anovan(allMin{animalInd},{allArea{animalInd},allSample{animalInd},},'model','full');
    [c,m] = multcompare(stats)
    allStatsTable=[allStatsTable;t(2,3) t(5,3) t(2,6) p(1)];
    [p,t,stats]=anovan(allMax{animalInd},{allArea{animalInd},allSample{animalInd},},'model','full');
    [c,m] = multcompare(stats)
    allStatsTable=[allStatsTable;t(2,3) t(5,3) t(2,6) p(1)];
end
allStatsTable=[allStatsTable(1:4,:) allStatsTable(5:8,:)];%monkey 1 in first 4 columns, monkey 2 in next four oclumns; 1st row: slope, 2nd: C50, 3rd: min, 4th: max
